.TH detwinner 1 "01 December 2019" "version 0.3.1"
.SH NAME
Detwinner - duplicate file finder for the Linux desktop
.SH SYNOPSIS
detwinner
.SH DESCRIPTION
.B detwinner
is the GTK3 application for searching and removing duplicated files and similar images.
.SH AUTHOR
Neat Decisions <opensource@neatdecisions.com>

