.TH detwinner 1 "03 September 2019" "version 0.2.1"
.SH NAME
Detwinner - duplicate file finder for GNOME environment
.SH SYNOPSIS
detwinner
.SH DESCRIPTION
.B detwinner
is the GTK3 application for searching and removing duplicated files and similar images.
.SH AUTHOR
Neat Decisions <opensource@neatdecisions.com>

